### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by JonnyRichardss** [alfieH0/Assignment-1#1]
The code seems very tidy and runs well. The use of an enum for 'suit' is particularly good in my opinion (it keeps the integer coding from the brief but also allows the suits to be named). 
I found a couple of errors related to dealing, the "dealCard" (multiple deal) method doesn't seem to remove cards from the pack and also the menu does not sanitize input when asking how many cards to deal, leading to an unhandled FormatException. 
A couple of minor nitpicks that I have are that the program doesn't have a way to handle when the pack is empty and that the printing of card names does not have spaces in, making it a little annoying to read. I would suggest tidying the CardName property a little.
Additionally, to touch on documentation, the code comments are a little sparse in places but the code is quite simple at the moment so I don't think they are strictly necessary at this point.
Overall very good in my opinion.

**Comment by alfieH0** [comment]
thanks for your feedback I've fixed the deal card method so it no longer produces an error and also fixed the menu input so It will no longer accept anything but numbers
