### ISSUE TITLE
Sam Crawshaw (25743539) Code review

### ISSUE THREAD

**Issue by SamCrawshawUOL** [alfieH0/Assignment-1#3]
The code compiles and runs well, though it could be commented a little more thoroughly to explain the thought process behind design choices. It handles erroneous inputs somewhat well by looping back but does not inform the user of their incorrect inputs so this could perhaps be useful to add. The program can also be a little awkward to close using only the console as it requires a few enter key presses to navigate between menus though these are not explicitly asked for. lastly, there is a logic error in the riffle shuffle that results in the deck being constructed incorrectly. At present, it sorts the deck into even values first and then odds on top when it should instead sort the array into the form [1, 27, 2, 28...]

**Comment by alfieH0** [comment]
thank you for the feedback I've made it so that when the user does an incorrect input it will explain to them the reason it was wrong as well as making the program easier to close from the console by adding an exit part to all menus I also fixed the logic error in riffle shuffle
